java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: YEAR after changing Date to Instant. I assume the db does not have the proper date format